exec-once = /home/$USER/.config/hypr/xdg.sh
exec-once = xwaylandvideobridge
exec-once = awww-daemon
exec-once = waybar & swaync
exec-once = swaync-client --change-cc-monitor $MONITOR_2
exec-once = swaync-client --change-noti-monitor $MONITOR_2
exec-once = vicinae server
# exec-once = AmneziaVPN
exec-once = telegram-desktop & ~/bin/pachca.AppImage & discord
exec-once = spotify
exec-once = obs --scene="replay" --startreplaybuffer
exec-once = sudo mouseless --config ~/.config/mouseless/config.yaml
