hl.on("hyprland.start", function()
    hl.exec_cmd("/home/$USER/.config/hypr/xdg.sh")
    hl.exec_cmd("xwaylandvideobridge")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar & swaync")
    hl.exec_cmd("swaync-client --change-cc-monitor $MONITOR_2")
    hl.exec_cmd("swaync-client --change-noti-monitor $MONITOR_2")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("throne")
    hl.exec_cmd("telegram-desktop & discord & ~/bin/Keet.AppImage & ~/bin/pachca.AppImage")
    hl.exec_cmd("spotify")
    hl.exec_cmd("sunshine")
    hl.exec_cmd("obs --scene=\"replay\" --startreplaybuffer")
    hl.exec_cmd("sudo mouseless --config ~/.config/mouseless/config.yaml")
end)

