-- ─────────────────────────────────────────────
-- Auto-assign windows to workspaces
-- (equivalent to i3 assign + for_window workspace)
-- ─────────────────────────────────────────────

-- Obsidian → workspace 6
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "obsidian",
    match = {
        class = "obsidian",
    },
    workspace = "6",
})

-- Discord + Telegram + Pachca → workspace 7
hl.window_rule({
    name = "TelegramDesktop",
    match = {
        class = "^(org\\.telegram\\.desktop)$",
    },
    workspace = "7",
    group = "set",
})

hl.window_rule({
    name = "Discord",
    match = {
        class = "discord",
    },
    workspace = "7",
    group = "set",
})

hl.window_rule({
    name = "pachca",
    match = {
        class = "Pachca",
    },
    workspace = "7",
    group = "set",
})

hl.window_rule({
    name = "Keet",
    match = {
        class = "Keet",
    },
    workspace = "7",
    group = "set",
})

-- Spotify → workspace 8
hl.window_rule({
    name = "Spotify",
    match = {
        class = "Spotify",
    },
    workspace = "8",
})

-- OBS Studio → workspace 10
hl.window_rule({
    name = "obs",
    match = {
        class = "com.obsproject.Studio",
    },
    workspace = "10",
})

-- AmneziaVPN → workspace 11
hl.window_rule({
    name = "amneziavpn",
    match = {
        class = "AmneziaVPN",
    },
    float = false,
    workspace = "11",
})

-- v2rayN → workspace 11
hl.window_rule({
    name = "v2rayN",
    match = {
        class = "v2rayN",
    },
    workspace = "11",
})

-- happ → workspace 11
hl.window_rule({
    name = "happ",
    match = {
        class = "happ",
    },
    workspace = "11",
})

-- throne → workspace 11
hl.window_rule({
    name = "throne",
    match = {
        class = "Throne",
    },
    workspace = "11",
})

-- Optional: open silently (no focus/switch) – very useful for startup apps
-- windowrulev2 = workspace 7 silent, class:^(discord)$

-- ─────────────────────────────────────────────
-- Try to emulate "layout tabbed" using groups
-- (best-effort – not perfect without hy3)
-- ─────────────────────────────────────────────

-- When these apps open → put them into a group automatically
-- (you can later use mod + G / mod + tab / etc to manage the group)

-- Example windowrule v1
-- windowrule = float, ^(kitty)$
-- Example windowrule v2
-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- https://itsohen.github.io/hyprrulefix/ v2 -> v3
hl.window_rule({
    name = "windowrule-1",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name = "windowrule-2",
    match = {
        title = "^(Picture(-|\\s)in(-|\\s)(p|P)icture)$",
    },
    float = true,
    pin = true,
})

hl.window_rule({
    name = "windowrule-3",
    match = {
        class = "org.pulseaudio.pavucontrol",
    },
    float = true,
    size = "(monitor_w*0.5) (monitor_h*0.5)",
})

hl.window_rule({
    name = "tilix",
    match = {
        class = "tilix",
    },
    opacity = "0.95 0.95",
})

-- windowrule {
--   name = ghostty
--   opacity = 0.95 0.95
--   match:class = com.mitchellh.ghostty
-- }

hl.window_rule({
    name = "windowrule-4",
    match = {
        class = "nemo",
    },
    float = true,
    size = "(monitor_w*0.5) (monitor_h*0.5)",
})

hl.window_rule({
    name = "satty",
    match = {
        class = "com.gabm.satty",
    },
    float = true,
    size = "(monitor_w*0.75) (monitor_h*0.75)",
})

hl.window_rule({
    name = "TelegramDesktopMediaViewer",
    match = {
        class = "org.telegram.desktop",
        title = "^Media viewer$",
    },
    fullscreen = false,
})

-- windowrule {
--   name = windowrule-5
--   float = on
--   size = (monitor_w*0.5) (monitor_h*0.5)
--   match:class = zen
--   match:title = ^Zen Browser$
-- }

-- windowrulev2 = noborder,class:^(zen)$,title:^(Picture-in-Picture)$
-- windowrulev2 = pin,class:^(zen)$,title:^(Picture-in-Picture)$
-- windowrulev2 = float,class:^(zen)$,title:^(Picture-in-Picture)$

hl.window_rule({
    name = "bitwarden",
    match = {
        class = "zen",
        title = "^(Bitwarden)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-9",
    match = {
        class = "^(com.github.hluk.copyq)$",
    },
    float = true,
})

-- Prevent tooltips from taking focus (always have a title of `win.<id>`)
hl.window_rule({
    name = "windowrule-10",
    match = {
        class = "^(.*jetbrains.*)$",
        title = "^(win.*)$",
    },
    no_initial_focus = true,
})

-- Make "Go to file" and other dialogs always focused when open
hl.window_rule({
    name = "windowrule-11",
    match = {
        class = "^(.*jetbrains.*)$",
        title = "^$",
        float = 1,
    },
    stay_focused = true,
})

-- fix tab dragging (always have a single space character as their title)
hl.window_rule({
    name = "windowrule-12",
    match = {
        class = "^(.*jetbrains.*)$",
        title = "^\\\\s$",
    },
    no_initial_focus = true,
})

-- Tile new tabs automatically
hl.window_rule({
    name = "windowrule-13",
    match = {
        class = "^(jetbrains-*)",
        float = 0,
    },
    float = false,
})

-- Fix splash screen showing in weird places and prevent annoying focus takeovers
hl.window_rule({
    name = "windowrule-14",
    match = {
        class = "^(jetbrains-.*)$",
        title = "^(splash)$",
        float = 1,
    },
    tag = "+jetbrains-splash",
})

hl.window_rule({
    name = "windowrule-15",
    match = {
        tag = "jetbrains-splash",
    },
    center = true,
    no_focus = true,
    border_size = 0,
})

-- Center popups/find windows
hl.window_rule({
    name = "windowrule-16",
    match = {
        class = "^(jetbrains-.*)",
        title = "^()$",
        float = 1,
    },
    tag = "+jetbrains",
    min_size = "(monitor_w*0.5) (monitor_h*0.5)",
})

hl.window_rule({
    name = "windowrule-17",
    match = {
        tag = "jetbrains",
    },
    center = true,
    stay_focused = true,
    border_size = 0,
})

-- Enabling this makes it possible to provide input in popup dialogs (search window, new file, etc.)

-- For some reason tag:jetbrains does not work for size rule

-- Disable window flicker when autocomplete or tooltips appear
hl.window_rule({
    name = "windowrule-18",
    match = {
        class = "^(jetbrains-.*)$",
        title = "^(win.*)$",
        float = 1,
    },
    no_initial_focus = true,
})

-- # Disable mouse focus
-- windowrule = nofollowmouse, class:^(jetbrains-.*)$

-- windowrule {
--   name = windowrule-25
--   opacity = 0.98 0.98
--   match:class = ^(jetbrains-.*)$
-- }
--
-- windowrule {
--   name = windowrule-26
--   opacity = 0.9 0.9
--   match:class = spotify
-- }
--
-- windowrule {
--   name = windowrule-goland
--   opacity = 0.9 0.9
--   match:class = jetbrains-goland
-- }

--Float Steam windows by default, but tile main client if desired
-- TODO: manual review — top-level key '; windowrule = float, class:^()$,title:^(Steam - Self Updater)$' has no enclosing section

hl.window_rule({
    name = "windowrule-27",
    match = {
        class = "^(steam)$",
    },
    float = true,
})

-- Tile specific Steam sub-windows (e.g., Friends List) to avoid floating everything
hl.window_rule({
    name = "windowrule-28",
    match = {
        class = "^(steam)$",
        title = "Friends List",
    },
    float = false,
    size = "(monitor_w*0.3) (monitor_h*1)",
})

hl.window_rule({
    name = "windowrule-29",
    match = {
        class = "^(steam)$",
        title = "Steam",
    },
    float = false,
    size = "(monitor_w*0.7) (monitor_h*1)",
})

-- Fix disappearing dropdown menus in Steam (common XWayland issue)
hl.window_rule({
    name = "windowrule-30",
    match = {
        title = "^()$",
        class = "^(steam)$",
    },
    stay_focused = true,
    min_size = "1 1",
})

-- Minimum size for Friends List popup to prevent tiny windows
hl.window_rule({
    name = "windowrule-31",
    match = {
        class = "^(steam)$",
        title = "^(Friends.*)$",
    },
    min_size = "280 635",
})

-- Assign Steam to a specific workspace (e.g., workspace 9)
-- Split Steam and Friends List windows (e.g., 70% main, 30% friends)
-- Fullscreen all games (ignores borders for immersion)
hl.window_rule({
    name = "windowrule-32",
    match = {
        class = "^(gamescope)$",
    },
    fullscreen = true,
})

hl.window_rule({
    name = "windowrule-33",
    match = {
        class = "^(steam_app_.*)$",
    },
    fullscreen = true,
    opacity = "1.0 override",
})

-- Force opacity 1.0 for fullscreen games (prevents transparency issues)
hl.window_rule({
    name = "windowrule-34",
    match = {
        fullscreen = 1,
    },
    opacity = "1.0 override",
})

-- Example for a specific game (e.g., Path of Exile, appid 238960)
hl.window_rule({
    name = "windowrule-35",
    match = {
        class = "^(steam_app_238960)$",
    },
    fullscreen = true,
})

-- Mark windows as "game" content for better handling (e.g., immediate focus)
hl.window_rule({
    name = "windowrule-36",
    match = {
        content = "game",
    },
    immediate = true,
})

hl.window_rule({
    name = "windowrule-37",
    match = {
        initial_class = "^(steam_app_\\d+)$",
    },
    content = "game",
})


hl.window_rule({
    name = "hide_env_edit",
    no_screen_share = true,
    match = {
        class = "^(jetbrains-webstorm|com.mitchellh.ghostty)$",
        title = ".*\\.env.*"
    }
})
