# Copy yanked files to the system clipboard
[[mgr.prepend_keymap]]
on  = "y"
run = [ "yank", 'plugin clipboard -- --action=copy' ]

# Paste files from the system clipboard into the current directory
[[mgr.prepend_keymap]]
on  = "<C-p>"
run = [ 'plugin clipboard -- --action=paste' ]

[[mgr.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
